# Generated by Django 4.1.1 on 2022-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='compensation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
