# Generated by Django 4.1.1 on 2022-10-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_alter_usereducation_user'),
        ('hirer', '0002_alter_opportunities_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity', to='hirer.opportunities'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='talent.user'),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='hirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirer_positions', to='hirer.hirer'),
        ),
    ]
